-- Seed data for 21 Hydrocean Tech products & 2 categories
DELETE FROM public.products;
DELETE FROM public.categories;

INSERT INTO public.categories (id, name, slug, description, icon_name, sort_order) VALUES ('c1000000-0000-0000-0000-000000000001', 'Purifiers', 'purifiers', 'Multi-stage domestic RO, UV, UF purifiers and filter kits', 'Droplets', 1);
INSERT INTO public.categories (id, name, slug, description, icon_name, sort_order) VALUES ('c1000000-0000-0000-0000-000000000002', 'RO', 'ro', 'High capacity commercial RO systems, coolers, and membranes', 'ShieldCheck', 2);


INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000001', 'c1000000-0000-0000-0000-000000000001', 'Lexcru Lexzon', 'lexcru-lexzon', 'Multi-stage RO+UV with transparent 10L tank • Free doorstep installation', 'Lexcru Lexzon delivers multi-stage RO+UV+UF water purification designed specifically for residential kitchens and high-TDS municipal or borewell sources. Features a crystal-clear 10-liter food-grade storage chamber, automatic tank-full shutoff, and long-life high-rejection RO membrane.', 6800, 11000, 38, '["/images/products/lexcru-lexzon.jpg"]'::jsonb, 'BEST VALUE', 'RO+UV', 4.8, 94, 'RO + UV + UF', '10L', '[{"capacity": "10L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + UF + Carbon Polish", "Storage Capacity": "10 Litres Food-Grade Tank", "Flow Rate": "12 to 15 LPH Output", "TDS Range": "Handles up to 2000 PPM TDS", "Mounting": "Wall Mount / Countertop", "Warranty": "1-Year Doorstep Comprehensive Service"}'::jsonb, '["Advanced multi-stage RO+UV+UF filtration cascade", "10L transparent food-grade antibacterial storage reservoir", "Automatic flushing valve to enhance membrane lifespan", "High-efficiency booster pump with whisper-quiet operation", "Includes complete installation kit and certified technician visit"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000002', 'c1000000-0000-0000-0000-000000000001', 'Water mark PURIFIER', 'water-mark-purifier', 'Smart TDS controller with LED purity indicators • 100% genuine filters', 'The Water Mark Purifier combines micro-filtration precision with an active TDS control valve to preserve essential minerals in your drinking water. Engineered with heavy-duty ABS body and food-grade components suitable for borewell, tanker, and municipal water.', 7200, 11000, 35, '["/images/products/water-mark-purifier.jpg"]'::jsonb, 'HIGH DEMAND', 'TDS CONTROL', 4.9, 82, 'RO + UV + TDS Control', '10L', '[{"capacity": "10L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + Micro-TDS Controller", "Storage Capacity": "10 Litres Clear Tank", "Flow Rate": "15 LPH Continuous Purify", "TDS Range": "Up to 2200 PPM TDS", "Cabinet": "Scratch-Resistant ABS Shell", "Warranty": "1-Year Hydrocean Certified Warranty"}'::jsonb, '["Micro-TDS manual controller for optimal taste customization", "Dual-color LED power and purification indicator panel", "Food-grade non-toxic storage chamber with dust seal", "NSF certified high-absorption activated carbon block", "Quick-connect push fittings for leak-proof performance"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000003', 'c1000000-0000-0000-0000-000000000001', 'AQUA MARS', 'aqua-mars', '12L high-capacity storage with alkaline pH booster • Rapid flow tap', 'Aqua Mars is engineered for medium to large families, featuring an expansive 12-liter tank and alkaline post-filter that maintains a healthy pH level of 7.5 to 8.5. Efficiently strips out toxic heavy metals, arsenic, fluorides, and microbes.', 6500, 11000, 41, '["/images/products/aqua-mars.jpg"]'::jsonb, 'POPULAR', 'ALKALINE', 4.7, 115, 'RO + UV + UF + Alkaline', '12L', '[{"capacity": "12L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + UF + Mineral Alkaline Cartridge", "Storage Capacity": "12 Litres Large Reservoir", "Flow Rate": "Up to 15 Litres Per Hour", "TDS Range": "Borewell & Municipal up to 2500 PPM", "Body Finish": "Curved Aesthetic Gloss Cyan/White", "Warranty": "1-Year On-Site Service"}'::jsonb, '["12-liter high-capacity storage chamber for uninterrupted water", "Alkaline pH infusion enhances hydration and antioxidant properties", "Stainless steel 11W germicidal UV disinfection chamber", "Auto-cut off sensor prevents water tank overflow", "Low maintenance cost with standard universal filter dimensions"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000004', 'c1000000-0000-0000-0000-000000000001', 'All filters', 'all-filters', 'Complete replacement filter kit: Sediment, Carbon Block, Inline Post Carbon & Spun Candle', 'Universal annual maintenance filter set compatible with all domestic RO water purifier models. Includes 1x high-density 5-micron spun polypropylene sediment filter, 1x pre-carbon block cartridge, 1x inline sediment cartridge, and 1x post-carbon taste polishing cartridge plus push-fit elbow fittings.', 750, 1500, 50, '["/images/products/all-filters.jpg"]'::jsonb, 'OEM SPARES', 'FILTER KIT', 4.9, 210, 'Universal RO Replacement Cartridges', 'Universal Spares', '[{"capacity": "Universal Spares", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Kit Components": "Pre-Filter Spun + Inline Sediment + Carbon Block + Post Carbon", "Micron Rating": "5 Micron Sediment Filtration", "Compatibility": "Universal (Fits Lexcru, Aqua, Kent, Dolphin, etc.)", "Lifespan": "6 to 12 Months (based on raw water TDS)", "Media": "100% Virgin Polypropylene & Coconut Shell Carbon", "Warranty": "Guaranteed 100% Genuine NSF Grade Media"}'::jsonb, '["Complete 4-piece replacement filter set for comprehensive servicing", "Removes chlorine, silt, suspended particles, sand, and organic odors", "High-iodine 1100 IV active carbon restores natural spring taste", "Standard 1/4-inch push-fit elbow connectors included in box", "Cost-effective DIY maintenance or book certified doorstep install"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000005', 'c1000000-0000-0000-0000-000000000001', 'AQUA GLANCE', 'aqua-glance', 'Transparent viewing window reveals inline filtration stages • Fast flow tap', 'Aqua Glance features a transparent modular cabinet showcasing its multi-stage inline filter cylinders and pure water reservoir. Backed by an 80 GPD high-flow RO membrane and high-intensity UV sterilizer to eliminate bacterial contamination.', 6500, 11000, 41, '["/images/products/aqua-glance.jpg"]'::jsonb, 'TRANSPARENT TANK', 'RO+UV+UF', 4.8, 76, 'RO + UV + UF', '10L', '[{"capacity": "10L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + UF + Taste Enhancer", "Storage Capacity": "10 Litres Split Transparent Chamber", "Flow Rate": "12 to 14 LPH", "TDS Range": "Up to 2000 PPM", "Mounting": "Wall Mount Ready", "Warranty": "1-Year Doorstep Warranty"}'::jsonb, '["Full crystal-clear transparent front panel with stage indicators", "Multi-stage inline purification with heavy-duty booster pump", "High recovery rate with efficient membrane architecture", "Detachable drip tray and ergonomic push dispensing tap", "Food-grade BPA-free materials ensuring zero secondary contamination"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000006', 'c1000000-0000-0000-0000-000000000001', 'AQUA C3', 'aqua-c3', 'Space-saving under-the-counter system with hydrostatic tank & chrome faucet', 'Aqua C3 is the ultimate space-saving under-sink (Under-the-Counter UTC) water purification system. Conceals all filtration components neatly beneath your kitchen sink, dispensing purified RO water via a designer chrome gooseneck countertop faucet.', 7500, 11000, 32, '["/images/products/aqua-c3.jpg"]'::jsonb, 'UNDER-SINK UTC', 'COMPACT', 4.9, 89, 'Under-sink / UTC RO', '8L', '[{"capacity": "8L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"System Type": "Under-the-Counter (UTC) Under-Sink", "Storage Tank": "8 Litre Pressurized Hydrostatic Steel/Polymer Tank", "Dispenser": "Chrome Gooseneck Designer Faucet Included", "Purification Stages": "RO + UV + UF + Mineral Cartridge", "TDS Handling": "Up to 2200 PPM TDS", "Warranty": "1-Year Complete On-Site Warranty"}'::jsonb, '["Frees up 100% of kitchen countertop and wall space", "Pressurized hydrostatic tank delivers high-velocity water flow", "Designer stainless steel / chrome countertop faucet included", "Leak-detector sensor with automatic shutoff valve", "Concealed vibration dampeners for ultra-silent operation"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000007', 'c1000000-0000-0000-0000-000000000001', 'Dolphin Aqua', 'dolphin-aqua', 'Classic curved dolphin body with float ball water level indicator', 'The iconic Dolphin Aqua is a proven residential workhorse recognized for its curved ergonomic cabinet and dependable performance. Equipped with dual-tone ABS body, high-pressure pump, and reliable RO+UV technology suitable for city and apartment pipelines.', 6000, 9000, 33, '["/images/products/dolphin-aqua.jpg"]'::jsonb, 'DOLPHIN SERIES', 'CLASSIC RO', 4.7, 142, 'RO + UV', '9L', '[{"capacity": "9L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + Pre/Post Filtration", "Storage Capacity": "9 Litres Food-Grade Tank", "Flow Rate": "10 to 12 LPH Flow", "TDS Range": "Up to 1800 PPM TDS", "Indicator": "Floating Red/White Water Level Indicator Ball", "Warranty": "1-Year Doorstep Warranty"}'::jsonb, '["Ergonomic dolphin-style contoured cabinet with wall brackets", "Visual float-ball level indicator for instant water volume checks", "Proven heavy-duty booster pump with thermal overload protection", "Universal filter element architecture for low annual maintenance", "100% food-grade plastic components with antimicrobial tank"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000008', 'c1000000-0000-0000-0000-000000000001', 'AQUA JADE', 'aqua-jade', 'Glossy emerald jade trim with digital display & active copper infusion', 'Aqua Jade introduces a luxury aesthetic to kitchen purification with its deep emerald green accents and digital status interface. Integrates an active copper and alkaline cartridge that enriches water with essential trace minerals and balanced alkalinity.', 6500, 12000, 46, '["/images/products/aqua-jade.jpg"]'::jsonb, 'EMERALD FINISH', 'ACTIVE COPPER', 4.8, 68, 'RO + UV + Alkaline Copper', '10L', '[{"capacity": "10L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + Active Copper + Alkaline pH", "Storage Capacity": "10 Litres Detachable Tank", "Flow Rate": "14 LPH", "TDS Range": "Up to 2400 PPM TDS", "Finish": "Gloss Emerald Jade Green with Pearl White", "Warranty": "1-Year Comprehensive Warranty"}'::jsonb, '["Active copper cartridge infuses natural antibacterial copper ions", "Digital smart display monitors TDS levels and purification status", "High-retention thin-film composite RO membrane", "Detachable water tank for effortless periodic cleaning", "Energy-efficient auto-flush mechanism saves water"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000009', 'c1000000-0000-0000-0000-000000000002', 'COMMERCIAL 30 to 50 LPH RO', 'commercial-30-to-50-lph-ro', 'Heavy-duty SS304 skid frame with dual membrane vessels & pressure gauges', 'Commercial skid-mounted 30 to 50 LPH RO water plant built on a robust stainless steel structure. Equipped with dual 20-inch jumbo pre-filter housings, dual commercial RO membranes, high-pressure brass vane pump, and dual analog pressure gauges for cafes, schools, and small offices.', 22000, 38000, 42, '["/images/products/commercial-30-to-50-lph-ro.jpg"]'::jsonb, 'COMMERCIAL PLANT', '30-50 LPH', 4.9, 53, 'Commercial Skid RO (30-50 LPH)', 'Continuous 50 LPH', '[{"capacity": "Continuous 50 LPH", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Capacity": "30 to 50 Litres Per Hour Continuous Flow", "Skid Construction": "Heavy-Duty Food Grade SS304 Stainless Steel", "Pre-Filtration": "Dual 20-Inch Jumbo Blue Housings (Sediment + Carbon)", "Membranes": "Dual Commercial High-Rejection TFC Elements", "Pump": "High-Pressure Commercial Rotary Pump with Pressure Gauges", "Warranty": "1-Year Commercial Site Warranty + Service Support"}'::jsonb, '["Delivers 30 to 50 liters/hour high-volume drinking water", "Sturdy stainless steel floor-standing skid with anti-vibration mounts", "Dual glycerin-filled pressure gauges for real-time monitoring", "High recovery system with adjustable reject-water control valve", "Ideal for offices with 30-100 staff, cafes, clinics, and restaurants"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000010', 'c1000000-0000-0000-0000-000000000002', 'COMMERCIAL RO', 'commercial-ro', 'Triple 20-inch pre-filter bracket with dual commercial booster pumps', 'Heavy-duty wall bracket commercial RO unit engineered for corporate cafeterias, bakeries, and gym centers. Features triple 20-inch pre-filtration stages to safeguard the dual RO membranes against high sediment loads.', 14000, 21000, 33, '["/images/products/commercial-ro.jpg"]'::jsonb, 'OFFICE & CAFE', 'HEAVY DUTY', 4.8, 61, 'Commercial Bracket RO 25-35 LPH', 'High Output', '[{"capacity": "High Output", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Capacity": "25 to 35 Litres Per Hour", "Mounting": "Heavy-Duty Epoxy Powder-Coated Wall Bracket", "Housings": "Triple 20-Inch Tall Filter Canisters", "Pumps": "Dual Commercial High-Flow Booster Pumps", "Inlet TDS": "Handles harsh borewell water up to 3000 PPM", "Warranty": "1-Year On-Site Service Warranty"}'::jsonb, '["Triple-stage pre-filtration eliminates heavy dirt and sediment", "Dual parallel booster pumps guarantee constant operating pressure", "Compact wall-hung design preserves floor space in commercial kitchens", "Standard 20-inch filter elements available everywhere at low cost", "Includes commercial brass ball valves and high-pressure tubing"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000011', 'c1000000-0000-0000-0000-000000000002', 'LX TWO', 'lx-two', 'Lexcru LX-2 series with matte navy cabinet, LED indicators & copper infuser', 'Lexcru LX-2 (LX TWO) represents next-generation domestic purification with its matte white and navy blue finish, LED system indicators, and active copper mineralizer. Engineered for demanding water quality conditions.', 10000, 15000, 33, '["/images/products/lx-two.jpg"]'::jsonb, 'LEXCRU SERIES', 'PREMIUM', 4.9, 73, 'RO + UV + Copper', '10L', '[{"capacity": "10L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "7-Stage RO + UV + UF + Active Copper", "Storage Capacity": "10 Litres Transparent Reservoir", "Flow Rate": "15 LPH Purification Speed", "TDS Range": "Up to 2500 PPM", "Design": "Architectural Matte Finish Wall Unit", "Warranty": "1-Year Doorstep Comprehensive Service"}'::jsonb, '["Contemporary architectural matte navy and white body", "Active copper mineralizer replenishes healthy micronutrients", "Multi-color LED status indicators for power, tank full, and service", "High-rejection 80 GPD membrane with 95%+ salt reduction", "Full installation kit and complimentary TDS water test included"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000012', 'c1000000-0000-0000-0000-000000000002', 'All Types Of membranes', 'all-types-of-membranes', 'Spiral-wound thin film composite (TFC) RO membrane rolls • 97% salt rejection', 'Authentic spiral-wound Thin Film Composite (TFC) Reverse Osmosis membrane filter rolls available in 75 GPD, 80 GPD, and 100 GPD capacities. Features precision 0.0001 micron filtration that rejects dissolved solids, arsenic, fluorides, lead, and viruses with up to 97% efficiency.', 800, 1800, 56, '["/images/products/all-types-of-membranes.jpg"]'::jsonb, 'HIGH REJECTION', 'MEMBRANE ROLL', 5.0, 189, 'TFC RO Membrane Roll Elements (75/80/100 GPD)', 'Replacement Element', '[{"capacity": "Replacement Element", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Membrane Type": "Spiral-Wound Thin-Film Composite (TFC) Roll", "Available Capacities": "75 GPD / 80 GPD / 100 GPD", "Pore Size": "0.0001 Micron (Molecular Filtration)", "Salt Rejection": "95% - 98% TDS Reduction Rate", "Compatibility": "Fits all standard 1812 domestic RO membrane housings", "Operating Pressure": "50 to 125 PSI"}'::jsonb, '["Authentic high-surface area spiral-wound membrane sheet construction", "Removes dissolved chemical salts, heavy metals, cysts, and pesticides", "Standard size 1812 fits virtually all residential RO membrane housings", "Equipped with central permeate collector pipe and rubber chevron seal", "Available in multiple GPD ratings to match your home''s water pressure"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000013', 'c1000000-0000-0000-0000-000000000002', 'AQUA NEEO', 'aqua-neeo', 'Angular geometric cabinet with cyan LED ribbon & 12-liter storage', 'Aqua Neeo stands out with its angular geometric front architecture and integrated cyan glow status ribbon. Boasts a massive 12-liter storage capacity and comprehensive multi-stage filtration to convert hard borewell water into crisp drinking water.', 9500, 14500, 34, '["/images/products/aqua-neeo.jpg"]'::jsonb, 'GEOMETRIC DESIGN', '12L TANK', 4.8, 78, 'RO + UV + Mineral Cartridge', '12L', '[{"capacity": "12L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + UF + Active Bio-Minerals", "Storage Capacity": "12 Litres Large Food-Grade Tank", "Flow Rate": "15 LPH Rapid Purification", "TDS Range": "Handles up to 2200 PPM TDS", "Finish": "Pearl White with Cyan Geometric Accents", "Warranty": "1-Year Complete Warranty"}'::jsonb, '["Distinctive faceted geometric cabinet design with cyan glow line", "Generous 12-liter storage tank handles peak household demand", "UV sterilizer kills 99.99% of pathogenic viruses and bacteria", "Active mineral cartridge balances mineral composition and taste", "Smooth dispensing faucet with high flow rate"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000014', 'c1000000-0000-0000-0000-000000000002', 'AQUA ALIVE', 'aqua-alive', 'Restores living natural minerals with multi-stage cascade • 10L capacity', 'Aqua Alive focuses on living water health by reinjecting essential calcium and magnesium ions after reverse osmosis filtration. Featuring an antibacterial 10-liter tank, high-pressure pump, and modern kitchen styling.', 9000, 14000, 36, '["/images/products/aqua-alive.jpg"]'::jsonb, 'ACTIVE MINERALS', 'RO+UV+UF', 4.8, 64, 'RO + UV + UF + Active Minerals', '10L', '[{"capacity": "10L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + UF + Mineral Cartridge", "Storage Capacity": "10 Litres Clear Tank", "Flow Rate": "14 LPH", "TDS Range": "Up to 2000 PPM", "Finish": "Deep Aqua Blue and White", "Warranty": "1-Year On-Site Warranty"}'::jsonb, '["Mineral restoration cartridge infuses optimal calcium & magnesium", "High-capacity 10-liter antibacterial storage chamber", "Dual LED indicators for purification and tank full notifications", "Universal filter element compatibility for easy long-term maintenance", "Certified technician doorstep delivery and installation included"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000015', 'c1000000-0000-0000-0000-000000000002', 'RO WITH COOLER', 'ro-with-cooler', 'Commercial stainless steel water cooler with in-built RO plant • Dual push taps', 'All-in-one commercial drinking water solution combining a heavy-duty food-grade SS304 stainless steel refrigerated water chiller with an integrated high-output multi-stage RO filtration plant. Features dual push taps (chilled water & ambient pure RO water) and a 40-liter refrigerated storage tank for schools, offices, factories, and community halls.', 35000, 45000, 22, '["/images/products/ro-with-cooler.jpg"]'::jsonb, 'RO + CHILLER', 'COLD & AMBIENT', 5.0, 41, 'Commercial RO + Water Cooler Chiller', '40L Cold Storage', '[{"capacity": "40L Cold Storage", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Unit Type": "Integrated Commercial Water Cooler with In-Built RO Plant", "Tank Capacity": "40 Litres SS304 Refrigerated Cooling Tank", "Cooling Rate": "20 to 40 Litres Per Hour Chilling Capacity", "Dispensing Taps": "2 Brass Chrome Push Taps (Chilled + Ambient Pure RO)", "Body Construction": "Heavy-Duty Corrosion-Resistant SS304 Stainless Steel", "Refrigerant": "Eco-Friendly R134a Compressor Cooling System", "Purification Stages": "Sediment + Pre-Carbon + RO Membrane 100 GPD + Post Carbon", "Warranty": "1-Year Comprehensive Commercial On-Site Warranty"}'::jsonb, '["Eliminates need for separate cooler and purifier\u2014all in one footprint", "Dual taps dispense crisp chilled RO water or room-temperature pure water", "Heavy-duty SS304 stainless steel construction inside and out", "Eco-friendly, energy-efficient high-capacity cooling compressor", "Ideal for high-footfall institutions, corporate offices, gyms, and colleges"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000016', 'c1000000-0000-0000-0000-000000000002', 'AQUA 9090', 'aqua-9090', 'Geometric diamond textured panel with manual MTDS controller • 11L tank', 'Aqua 9090 combines high-end aesthetic appeal with versatile purification. Featuring an architectural diamond-patterned front fascia, MTDS manual mineral control, and an 11-liter food-grade storage tank.', 10000, 18000, 44, '["/images/products/aqua-9090.jpg"]'::jsonb, 'DIAMOND FACET', 'MTDS', 4.9, 79, 'RO + UV + MTDS', '11L', '[{"capacity": "11L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + MTDS + Carbon Polish", "Storage Capacity": "11 Litres Antibacterial Chamber", "Flow Rate": "15 LPH Flow", "TDS Range": "Handles up to 2500 PPM", "Finish": "Diamond Texture Gloss Black & Chrome", "Warranty": "1-Year Hydrocean Certified Warranty"}'::jsonb, '["Designer diamond-faceted front panel elevates modern kitchen aesthetics", "Manual TDS controller adjusts mineral content for ideal drinking taste", "11-liter high-capacity tank ensures ample backup water during power cuts", "Automatic tank full shut-off and dry-run pump protection", "NSF certified filter cartridges for peak contaminant removal"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000017', 'c1000000-0000-0000-0000-000000000002', 'Aqua NINE', 'aqua-nine', 'Smart compact casing with high recovery membrane and 10L clean tank', 'Aqua Nine is crafted for compact residential apartments, delivering uncompromising 7-stage RO+UV+UF purification in a streamlined, wall-mounted footprint.', 8500, 14000, 39, '["/images/products/aqua-nine.jpg"]'::jsonb, 'COMPACT SMART', '10L TANK', 4.7, 58, 'RO + UV + UF', '10L', '[{"capacity": "10L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + UF + Taste Conditioner", "Storage Capacity": "10 Litres Food-Grade Tank", "Flow Rate": "12 to 14 LPH", "TDS Range": "Up to 2000 PPM TDS", "Finish": "Clean White with Deep Blue Trim", "Warranty": "1-Year On-Site Warranty"}'::jsonb, '["Space-saving wall-mount profile fits easily above kitchen counters", "Multi-stage filtration handles both ground borewell and piped water", "Food-grade non-toxic storage chamber keeps water fresh for days", "Energy-saving automatic flush and cut-off sensors", "Low operating and filter replacement maintenance costs"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000018', 'c1000000-0000-0000-0000-000000000002', 'Aqua ZURIC', 'aqua-zuric', 'Swiss-inspired minimalist purifier with alkaline mineral balancing • 10L', 'Aqua Zuric embodies Swiss minimalist engineering with its sleek charcoal accents and advanced alkaline water rebalancing. Effectively lowers high hardness while maintaining healthy mineral equilibrium.', 7800, 13000, 40, '["/images/products/aqua-zuric.jpg"]'::jsonb, 'SWISS DESIGN', 'ALKALINE', 4.8, 71, 'RO + UV + Alkaline', '10L', '[{"capacity": "10L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + Alkaline Mineral Cartridge", "Storage Capacity": "10 Litres Transparent Reservoir", "Flow Rate": "14 LPH", "TDS Range": "Up to 2200 PPM TDS", "Design": "Swiss-Inspired Minimalist Cabinet", "Warranty": "1-Year Comprehensive Warranty"}'::jsonb, '["Alkaline re-mineralization cartridge balances water pH to 8.0+", "Minimalist charcoal-trim aesthetic harmonizes with modern kitchens", "High-pressure booster pump operates quietly and efficiently", "10L transparent food-grade tank allows visual volume checking", "Includes doorstep delivery, unboxing, and certified installation"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000019', 'c1000000-0000-0000-0000-000000000002', 'Aqua 2090', 'aqua-2090', 'Dual copper and zinc infusion with 12L capacity and LED status indicators', 'Aqua 2090 blends contemporary dark styling with dual active copper and zinc immunity booster cartridges. Equipped with a large 12-liter storage tank to comfortably support large households.', 9500, 15000, 37, '["/images/products/aqua-2090.jpg"]'::jsonb, 'COPPER & ZINC', '12L TANK', 4.9, 92, 'RO + UV + Copper + Zinc', '12L', '[{"capacity": "12L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "RO + UV + Copper + Zinc + Carbon", "Storage Capacity": "12 Litres Large Tank", "Flow Rate": "15 LPH", "TDS Range": "Up to 2500 PPM", "Finish": "Metallic Grey and Copper Trim", "Warranty": "1-Year Doorstep Warranty"}'::jsonb, '["Infuses both copper and zinc for daily holistic wellness and immunity", "Large 12-liter water chamber handles large family drinking needs", "UV-C germicidal disinfection chamber kills bacteria and protozoa", "Sleek push faucet with continuous dispense lock mechanism", "Low-pressure cut-off prevents pump damage during water interruptions"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000020', 'c1000000-0000-0000-0000-000000000002', 'Aqua innovica', 'aqua-innovica', 'Smart touchscreen interface with digital live TDS display & filter health tracking', 'Aqua Innovica represents the pinnacle of intelligent kitchen purification. Features a glowing touchscreen front panel displaying live input/output TDS measurements, filter cartridge life status, and automatic self-cleaning flush cycles.', 12000, 19000, 37, '["/images/products/aqua-innovica.jpg"]'::jsonb, 'TOUCHSCREEN TDS', 'SMART RO', 5.0, 104, 'Smart RO + UV + Touchscreen TDS', '10L', '[{"capacity": "10L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "Smart 7-Stage RO + UV + UF + Digital MTDS", "Interface": "Real-Time Digital Touchscreen with Live TDS Display", "Storage Capacity": "10 Litres Antibacterial Tank", "Flow Rate": "16 LPH High Speed", "TDS Handling": "Handles up to 3000 PPM Extreme Hard Water", "Warranty": "1-Year Comprehensive On-Site Warranty"}'::jsonb, '["Real-time digital touchscreen monitors inlet and purified TDS levels", "Smart filter life tracker alerts before filter replacement is due", "Automated high-frequency flush cycles extend membrane life by 2x", "Piano black mirror-finish front panel with chrome water faucet", "Premium food-grade detachable tank with anti-bacterial lining"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);
INSERT INTO public.products (
  id, category_id, name, slug, short_description, full_description, price, compare_at_price, discount_percent, images, badge_text, tag_badge, rating, review_count, purification_tech, storage_capacity, capacity_variants, specifications, features, filtration_stages, is_featured, is_in_stock, is_published
) VALUES (
  'p1000000-0000-0000-0000-000000000021', 'c1000000-0000-0000-0000-000000000002', 'Aqua v5', 'aqua-v5', 'Vertical ribbed cabinet with silent booster pump & 7-stage cascade • 10L', 'Aqua V5 is engineered for quiet domestic efficiency, combining a noise-dampened booster pump with a rigorous 7-stage purification cascade. Its transparent reservoir and vertical fluted body add refined styling to any kitchen counter.', 10000, 17000, 41, '["/images/products/aqua-v5.jpg"]'::jsonb, 'SILENT PUMP', '7-STAGE', 4.8, 87, 'RO + UV + UF + Silent Booster', '10L', '[{"capacity": "10L", "price_diff": 0, "label": "Standard Model", "is_default": true}]'::jsonb, '{"Purification Stages": "7-Stage RO + UV + UF + Carbon Polish", "Storage Capacity": "10 Litres Clear Tank", "Flow Rate": "14 LPH", "TDS Range": "Up to 2200 PPM", "Motor": "Silent Dampened High-Torque Booster Pump", "Warranty": "1-Year Complete Doorstep Warranty"}'::jsonb, '["Acoustic noise-dampened booster pump operates with zero vibration", "Complete 7-stage cascade eliminates dissolved chemicals and heavy metals", "10L food-grade transparent tank allows effortless water level checking", "Auto-cut off sensor prevents water leakage and electrical surge issues", "Free doorstep technician installation and test kit included"]'::jsonb, '[{"stage": 1, "title": "Pre-Sediment Spun Filter", "description": "Removes sand, mud, and coarse physical dirt."}, {"stage": 2, "title": "Activated Carbon Block", "description": "Adsorbs harmful chlorine, bad taste, and foul odors."}, {"stage": 3, "title": "Reverse Osmosis Membrane", "description": "Pore size 0.0001 micron strips heavy metals and dissolved salts."}, {"stage": 4, "title": "Germicidal UV Disinfection", "description": "Instant sterilizer eliminates microbial pathogens and viruses."}, {"stage": 5, "title": "Post-Carbon Mineralizer", "description": "Restores essential minerals and balances natural taste."}]'::jsonb, true, true, true
);